name: libtalley
channels:
  - conda-forge
dependencies:
  - python >= 3.8
  - numpy >= 1.15.0
  - pandas
  - tabulate
  - unyt >= 2.8.0
  # Optional packages
  - matplotlib
  - xarray
  # Development
  - pytest
  - yapf
  - ipython
  - ipykernel
  - pip
  - pip:
    - '-e .'
