{% set data = load_setup_py_data() %}

package:
  name: libtalley
  version: {{ data.get('version') }}

source:
  git_url: "../"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.7.0
    - numpy>=1.15.0
    - pandas
    - requests
    - scipy>=1.0.0
    - tabulate
    - conda-forge::pint>=0.17.0

test:
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
