{% set data = load_setup_py_data() %}

package:
  name: libtalley
  version: {{ data.get('version') }}

source:
  path: ".."

build:
  noarch: python

requirements:
  host:
    - python
  run:
    - python>=3.7.0
    - numpy>=1.15.0
    - pandas
    - scipy>=1.0.0
    - tabulate
    - conda-forge::unyt>=2.8.0

test:
  imports:
    - libtalley
    - libtalley.asce7_16
    - libtalley.asce7_16.seismic
    - libtalley.fema_p695
    - libtalley.latex_format
    - libtalley.mutt
    - libtalley.steeldesign
    - libtalley.text
    - libtalley.units

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
